TENSORBOARD_PATH="Tensorboard"
DATASET_PATH="Mnist"
CHECKPOINT_PATH="My_GANs_Checkpoints.pth.tar"

BATCH_SIZE=32
EPOCHS=50
LEARNING_RATE=0.0003
HIDDEN_DIM=256
NOISE_DIM=100
IMG_SIZE=1*28*28

TRAIN=True
TEST_MODEL=True
VISUALIZE_DATA=True
LOAD_CHECKPOINT=False